#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : seabios
Version  : 1.9.1
Release  : 2
URL      : https://github.com/coreboot/seabios/archive/rel-1.9.1.tar.gz
Source0  : https://github.com/coreboot/seabios/archive/rel-1.9.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0
Requires: seabios-data
BuildRequires : acpica-unix2
Patch1: add-install-rule.patch
Patch2: seabios-add-E820-PRAM-type.patch

%description
Welcome to the SeaBIOS project!  This project implements an X86 legacy
bios that is built with standard GNU tools.

%package data
Summary: data components for the seabios package.
Group: Data

%description data
data components for the seabios package.


%prep
%setup -q -n seabios-rel-1.9.1
%patch1 -p1
%patch2 -p1

%build
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install PREFIX=%{buildroot}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/seabios/bios.bin
